#!/usr/bin/env bash
# smth
PIDFILE="/tmp/myscript.pid"

echo $$ > "$PIDFILE"

trap 'echo "I hate the kill command"; rm -f "$PIDFILE"; exit' SIGTERM
trap 'echo "Y U no love me?!"' SIGINT
trap 'rm -f "$PIDFILE"; exit' SIGQUIT

while true; do
  echo "To infinity and beyond"
  sleep 1
done
