#!/usr/bin/env bash
#smth
#!/bin/bash

for pid_path in /proc/[0-9]*; do
    pid=${pid_path#/proc/}
    if [ -f "$pid_path/comm" ]; then
        name=$(<"$pid_path/comm")
        if [[ "$name" == *bash* ]]; then
            echo "$pid $name"
        fi
    fi
done
